### ISSUE TITLE
Vite error: Invalid character

### ISSUE THREAD

**Issue by Li-Pro** [CMUH-CMAX/cmax_frontend#4]
進首頁後，一陣子 vite 會跳出 Invalid character error。
```
Invalid character
    at new DOMException (node:internal/per_context/domexception:53:5)
    at __node_internal_ (node:internal/util:695:10)
    at btoa (node:buffer:1268:13)
    at SourceMap.toUrl (file:///C:/Users/%E5%91%A8%E6%9A%98%E5%85%B8/Desktop/CMAX/cmax_frontend/app/node_modules/svelte/src/compiler/utils/mapped_code.js:295:60)
    at dom (file:///C:/Users/%E5%91%A8%E6%9A%98%E5%85%B8/Desktop/CMAX/cmax_frontend/app/node_modules/svelte/src/compiler/compile/render_dom/index.js:42:51)
    at compile (file:///C:/Users/%E5%91%A8%E6%9A%98%E5%85%B8/Desktop/CMAX/cmax_frontend/app/node_modules/svelte/src/compiler/compile/index.js:153:6)
    at compileSvelte (file:///C:/Users/%E5%91%A8%E6%9A%98%E5%85%B8/Desktop/CMAX/cmax_frontend/app/node_modules/@sveltejs/vite-plugin-svelte/src/utils/compile.js:126:20)
    at async handleHotUpdate (file:///C:/Users/%E5%91%A8%E6%9A%98%E5%85%B8/Desktop/CMAX/cmax_frontend/app/node_modules/@sveltejs/vite-plugin-svelte/src/handle-hot-update.js:29:17)
    at async handleHMRUpdate (file:///C:/Users/%E5%91%A8%E6%9A%98%E5%85%B8/Desktop/CMAX/cmax_frontend/app/node_modules/vite/dist/node/chunks/dep-df561101.js:41264:33)
    at async onHMRUpdate (file:///C:/Users/%E5%91%A8%E6%9A%98%E5%85%B8/Desktop/CMAX/cmax_frontend/app/node_modules/vite/dist/node/chunks/dep-df561101.js:65113:17
```

似乎是載入 `app/src/routes/search/+page.svelte` 時出的問題。

**Comment by Li-Pro** [comment]
一個 workaround，設定好 utf8 編碼，不確定妥不妥。
```diff
diff --git a/app/src/app.html b/app/src/app.html
index 2b31d0f..ba88ad9 100644
--- a/app/src/app.html
+++ b/app/src/app.html
@@ -4,6 +4,7 @@
 		<meta charset="utf-8" />
 		<link rel="icon" href="%sveltekit.assets%/favicon.png" />
 		<meta name="viewport" content="width=device-width" />
+		<meta charset="iso-8859-15" />
 		%sveltekit.head%
 	</head>
 	<body data-sveltekit-preload-data="hover" class="grid justify-center align-center">
```

@ZoneTwelve @jackshinshin

**Comment by Li-Pro** [comment]
[相關 issue](https://github.com/sveltejs/svelte/issues/6714)，似乎是檔名有多國語言的問題，可能是我路徑設定的關係。這個好像在 svelte 4.2.1 修好了。
